program: node2vec_wandb.py
method: grid
metric:
  name: loss
  goal: minimize
parameters:
  lr:
    values: [1e-2, 1e-3, 1e-4]
  batch_size:
    values: [512, 1024]
  walk_length:
    values: [3,5,10]
  context_size:
    values: [3,5,10]
  embedding_dim:
    values: [4,8,16]
  walks_per_node:
    values: [3,7,10]
