program: node2vec_wandb.py
method: grid
metric:
  name: loss
  goal: minimize
parameters:
  lr:
    values: [1e-2]
  batch_size:
    values: [128, 256]
  walk_length:
    values: [10, 15]
  context_size:
    values: [3]
  embedding_dim:
    values: [16, 32, 64]
  walks_per_node:
    values: [3]
